# On-disk install target (e.g. ODROID H2 with a SATA SSD).
#
# Unlike the live ISO, this is a persistent system with a real bootloader, so it
# boots from a fixed SATA disk, survives reboots (token/state persist), and can
# be updated in place with `nixos-rebuild switch`.
{ lib, pkgs, ... }:
{
  # disko's in-VM image builder (make-disk-image) builds the VM kernel with
  # `pkgs.aggregateModules`, whose output has no `.target`. This nixpkgs' vmTools
  # reads `kernel.target` to locate the bootable image, so the image build fails
  # with "kernel-modules has no target attribute". Re-attach it (bzImage on
  # x86_64) in the pkgs instance disko uses for image building only. Drop this
  # once disko upstream tracks the vmTools change.
  disko.imageBuilder.pkgs = pkgs.extend (final: prev: {
    aggregateModules = modules: (prev.aggregateModules modules).overrideAttrs (old: {
      passthru = (old.passthru or { }) // {
        target = "bzImage"; # x86_64 kernel image name (this target is x86_64-only)
      };
    });
  });

  imports = [
    # btrfs+zstd disk layout (disko). Provides fileSystems."/" and "/boot".
    ./disk-layout.nix
    # Automatic GC / store dedup / low-disk safety net. Persistent-target only:
    # the ephemeral ISO must not GC its read-only store.
    ../core/storage.nix
  ];

  nixpkgs.hostPlatform = "x86_64-linux";
  hardware.enableRedistributableFirmware = true;

  # systemd-boot installed at the *removable* fallback path (\EFI\BOOT\BOOTX64.EFI).
  # ODROID H2-class firmware won't auto-boot a bootloader from a fixed SATA disk
  # via an NVRAM entry alone, but it does honour the removable fallback — the
  # same mechanism that makes USB media boot. This is the crux of the fix.
  #
  # `bootctl install` copies systemd-bootx64.efi to the removable fallback path
  # automatically, so no separate "install as removable" knob is needed. With
  # canTouchEfiVariables = false it installs with --no-variables (no NVRAM entry).
  # configurationLimit bounds how many generations get boot entries + kernels
  # copied into the small vfat ESP, so /boot can't fill up. GC (see storage.nix)
  # prunes the corresponding store paths; together they keep the disk bounded.
  boot.loader.systemd-boot.enable = true;
  boot.loader.systemd-boot.configurationLimit = 3;
  boot.loader.efi.canTouchEfiVariables = false;

  # Enough to bring up SATA/NVMe/USB storage and HID in early boot.
  boot.initrd.availableKernelModules = [
    "ahci"
    "ata_piix"
    "xhci_pci"
    "ehci_pci"
    "nvme"
    "usb_storage"
    "sd_mod"
    "usbhid"
  ];
  boot.kernelModules = [ "kvm-intel" ];

  # fileSystems."/" and "/boot" are generated by disko from ./disk-layout.nix.
}
