# Raspberry Pi 4 (aarch64) hardware profile — SD-card image target.
#
# Delivery: a flashable SD image (NixOS's sd-image-aarch64 builder, u-boot +
# extlinux). Board specifics (firmware, kernel, v3d GPU) come from the
# nixos-hardware raspberry-pi-4 module wired in via flake.nix. Unlike the x86
# disk target there's no systemd-boot, so the Automatic Boot Assessment
# auto-rollback (bootCounting) doesn't apply here — manual rollback from the
# recovery UI still works (extlinux is regenerated by switch-to-configuration).
{ modulesPath, ... }:
{
  imports = [
    "${modulesPath}/installer/sd-card/sd-image-aarch64.nix"
  ];

  nixpkgs.hostPlatform = "aarch64-linux";

  # Broad Wi-Fi / device firmware, plus the Pi's own firmware blobs.
  hardware.enableRedistributableFirmware = true;

  # v3d GPU via the fake-KMS overlay, so Wayland/Chromium get hardware
  # acceleration instead of falling back to slow software rendering.
  hardware.raspberry-pi."4".fkms-3d.enable = true;

  # The card grows to fill on first boot (like the x86 image), so one image
  # fits any SD card / capacity.
  sdImage.compressImage = true;
}
