# Raspberry Pi 4 (aarch64) hardware profile — SD-card image target.
#
# Delivery: a flashable SD image (NixOS's sd-image-aarch64 builder, u-boot +
# extlinux). Board specifics (firmware, kernel, v3d GPU) come from the
# nixos-hardware raspberry-pi-4 module wired in via flake.nix. Unlike the x86
# disk target there's no systemd-boot, so the Automatic Boot Assessment
# auto-rollback (bootCounting) doesn't apply here — manual rollback from the
# recovery UI still works (extlinux is regenerated by switch-to-configuration).
{ modulesPath, lib, ... }:
{
  imports = [
    "${modulesPath}/installer/sd-card/sd-image-aarch64.nix"
  ];

  nixpkgs.hostPlatform = "aarch64-linux";

  # In-place updates: rebuild this config from the release tag. No systemd-boot
  # auto-rollback here (extlinux), but manual rollback from the recovery UI works.
  dashboard.update.installable = true;
  dashboard.update.flakeAttr = "dashboard-rpi4";

  # Boot chain: the GPU firmware can't read extlinux.conf, so the
  # generic-extlinux-compatible loader (enabled by the nixos-hardware pi4
  # module) needs U-Boot as an intermediary. This copies u-boot.bin onto the
  # firmware partition and points config.txt's kernel= at it (plus arm_64bit=1),
  # so start4.elf → u-boot.bin → extlinux.conf → Linux. Without it there is no
  # kernel on the FAT partition and the Pi flashes the green LED 7 times
  # ("kernel image not found") with a black screen.
  hardware.raspberry-pi.firmware.uboot.enable = true;

  # sd-image-aarch64 sets hardware.enableAllHardware, which pulls in a broad
  # initrd module list. That list is what makes the SD card usable: the SD host
  # controllers and ext4 are built into the linux-rpi kernel (CONFIG_MMC_SDHCI/
  # BCM2835/EXT4_FS=y), but the block layer that exposes the card as /dev/mmcblk0
  # is a module (CONFIG_MMC_BLOCK=m). Drop it and the systemd stage-1 root device
  # (/dev/disk/by-label/NIXOS_SD) never appears → boot times out in emergency mode.
  #
  # The catch: that same list also names DRM/SoC modules the linux-rpi kernel
  # doesn't ship, so the initrd module-closure fails at build time ("Module
  # dw-hdmi not found"). Rather than clearing the whole list (which also loses
  # mmc_block), disable only the offending modules and keep everything else.
  # See https://github.com/NixOS/nixpkgs/issues/154163
  boot.initrd.availableKernelModules = {
    dw-hdmi = lib.mkForce false;
    dw-mipi-dsi = lib.mkForce false;
    rockchipdrm = lib.mkForce false;
    rockchip-rga = lib.mkForce false;
    phy-rockchip-pcie = lib.mkForce false;
    pcie-rockchip-host = lib.mkForce false;
    pwm-sun4i = lib.mkForce false;
    sun4i-drm = lib.mkForce false;
    sun8i-mixer = lib.mkForce false;
  };

  # Broad Wi-Fi / device firmware, plus the Pi's own firmware blobs.
  hardware.enableRedistributableFirmware = true;

  # v3d GPU via the fake-KMS overlay, so Wayland/Chromium get hardware
  # acceleration instead of falling back to slow software rendering.
  hardware.raspberry-pi."4".fkms-3d.enable = true;

  # The card grows to fill on first boot (like the x86 image), so one image
  # fits any SD card / capacity.
  sdImage.compressImage = true;
}
